on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: clone-branch
        run: git clone https://github.com/Defirence/CSGO-Ping-Tester-redux.git
      - name: run-pylint-checks
        run: |
          echo "List and change into repo dir on runner..."
          ls -lah
          cd CSGO-Ping-Tester-redux
          ls -lah
          echo "Update packages and install Python3..."
          apt-get update -y
          apt-get upgrade -y
          apt-get dist-upgrade -y
          apt-get full-upgrade -y
          apt-get install python3 python3-pip -y
          echo "Running pylint checks against script..."
          pip install -r requirements.txt ; --exit-zero ./main.py