on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: clone-branch
      - uses: actions/checkout@v3
        run: git clone https://github.com/Defirence/CSGO-Ping-Tester-redux.git
      - name: run-pylint-checks
        run: |
          echo "Running pylint checks against script..."
          pip install -r requirements.txt ; --exit-zero ./main.py